# Generated by Django 4.2.29 on 2026-04-14 03:13

from django.db import migrations, models
import django.db.models.deletion


def map_legacy_order_status(apps, schema_editor):
    Order = apps.get_model('crm', 'Order')
    mapping = {
        'confirmed': 'pending_payment',
        'production': 'paid',
        'exception': 'pending',
    }
    for old, new in mapping.items():
        Order.objects.filter(status=old).update(status=new)


def rollback_legacy_order_status(apps, schema_editor):
    Order = apps.get_model('crm', 'Order')
    reverse_mapping = {
        'pending_payment': 'confirmed',
        'paid': 'production',
    }
    for old, new in reverse_mapping.items():
        Order.objects.filter(status=old).update(status=new)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_add_order_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerecord',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='crm.messagerecord'),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(map_legacy_order_status, rollback_legacy_order_status),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('pending_shipment', 'Pending Shipment'), ('shipped', 'Shipped'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
