# Generated by Django 4.2.29 on 2026-04-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_order_desc_status_and_message_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20),
        ),
    ]
